name: LocalShops
main: net.centerleft.localshops.LocalShops
version: 3.1.1
author: Cereal, Jonbas
description: >
             A localized shop plugin for use with Bukkit economies.
             Users can create and manage their own shops.
commands:
  lshop:
    description: Command for managing shops 
    usage: |
           /<command> - displays command help
    aliases: [shop, buy, sell]
