name: LocalShops
main: com.milkbukkit.localshops.LocalShops
version: 3.2.0dev
author: Cereal, Jonbas
description: >
             A localized shop plugin for use with Bukkit economies.
             Users can create and manage their own shops.
commands:
  lshop:
    description: Command for managing shops 
    usage: |
           /<command> - displays command help
    aliases: [shop]
  gshop:
    description: Command for managing global shop
    usage: |
           /<command> - displays command help
    aliases: [global]
  buy:
    description: Command for buying from a shop
    usage: |
           /<command> - displays command help
  sell:
    description: Command for selling to a shop
    usage: |
           /<command> - displays command help
  gbuy:
    description: Command for buying from the global shop
    usage: |
           /<command> - displays command help
  gsell:
    description: Command for selling to the global shop
    usage: |
           /<command> - displays command help
  lsadmin:
    description: Command for setting global LocalShops values
    usage: |
           /<command> - displays command help
